title: Neo's NVM
description: "Neo's Non-Volatile Memory space"
author:
  name: "Sungjun Park"
  email: "sungjun@photogrammer.me"
  url: "https://neo-nvm.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Neo"
year : "2025"
